name: npm audit 
on: 
  workflow_dispatch:
    inputs:
      source_tag:
        description: 'Source Image Tag'     
        required: true
        default: 'latest'
  schedule:
    - cron: '0 0 1 * *'
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: "12"
      - name: Install dependencies
        run: npm ci
      - name: Unit tests
        run: npm audit
  build: